package reaction_rules;

import sbnz.skincare.facts.Reaction;
import sbnz.skincare.facts.ProductReaction;
import sbnz.skincare.facts.drools.ReactionInput;

query isContainedIn( String x, String y )
  Reaction( x, y; )
  or
  ( Reaction( z, y; ) and isContainedIn( x, z; ) )
end

rule "Has reaction"
    when
        $pr: ProductReaction(reaction == null)
        $ri: ReactionInput($reaction: reaction, $symptom: symptom)
        isContainedIn($reaction, $symptom;)
    then
        System.out.println($symptom + " IS ELEMENT OF " + $reaction); 
        modify($pr) {
            setReaction(drools.getRule().getName())
        }
end
